import type { HLJSApi } from 'highlight.js';

// Import languages
import javascript from 'highlight.js/lib/languages/javascript';
import typescript from 'highlight.js/lib/languages/typescript';
import python from 'highlight.js/lib/languages/python';
import cpp from 'highlight.js/lib/languages/cpp';
import java from 'highlight.js/lib/languages/java';
import csharp from 'highlight.js/lib/languages/csharp';
import ruby from 'highlight.js/lib/languages/ruby';
import go from 'highlight.js/lib/languages/go';
import swift from 'highlight.js/lib/languages/swift';
import rust from 'highlight.js/lib/languages/rust';
import php from 'highlight.js/lib/languages/php';
import kotlin from 'highlight.js/lib/languages/kotlin';
import sql from 'highlight.js/lib/languages/sql';
import shell from 'highlight.js/lib/languages/shell';
import perl from 'highlight.js/lib/languages/perl';
import r from 'highlight.js/lib/languages/r';
import matlab from 'highlight.js/lib/languages/matlab';
import scala from 'highlight.js/lib/languages/scala';
import haskell from 'highlight.js/lib/languages/haskell';
import lua from 'highlight.js/lib/languages/lua';
import julia from 'highlight.js/lib/languages/julia';
import dart from 'highlight.js/lib/languages/dart';
import groovy from 'highlight.js/lib/languages/groovy';
import powershell from 'highlight.js/lib/languages/powershell';
import x86asm from 'highlight.js/lib/languages/x86asm';
import fortran from 'highlight.js/lib/languages/fortran';
import lisp from 'highlight.js/lib/languages/lisp';
import prolog from 'highlight.js/lib/languages/prolog';
import erlang from 'highlight.js/lib/languages/erlang';
import ocaml from 'highlight.js/lib/languages/ocaml';
import fsharp from 'highlight.js/lib/languages/fsharp';
import clojure from 'highlight.js/lib/languages/clojure';
import elixir from 'highlight.js/lib/languages/elixir';
import pascal from 'highlight.js/lib/languages/delphi';
import vhdl from 'highlight.js/lib/languages/vhdl';
import tcl from 'highlight.js/lib/languages/tcl';
import nim from 'highlight.js/lib/languages/nim';
import commonlisp from 'highlight.js/lib/languages/lisp';
import coffeescript from 'highlight.js/lib/languages/coffeescript';
import objectivec from 'highlight.js/lib/languages/objectivec';
import vbnet from 'highlight.js/lib/languages/vbnet';

// Register all languages
export function registerLanguages(hljs: HLJSApi): void {
  hljs.registerLanguage('javascript', javascript);
  hljs.registerLanguage('typescript', typescript);
  hljs.registerLanguage('python', python);
  hljs.registerLanguage('cpp', cpp);
  hljs.registerLanguage('java', java);
  hljs.registerLanguage('csharp', csharp);
  hljs.registerLanguage('ruby', ruby);
  hljs.registerLanguage('go', go);
  hljs.registerLanguage('swift', swift);
  hljs.registerLanguage('rust', rust);
  hljs.registerLanguage('php', php);
  hljs.registerLanguage('kotlin', kotlin);
  hljs.registerLanguage('sql', sql);
  hljs.registerLanguage('shell', shell);
  hljs.registerLanguage('perl', perl);
  hljs.registerLanguage('r', r);
  hljs.registerLanguage('matlab', matlab);
  hljs.registerLanguage('scala', scala);
  hljs.registerLanguage('haskell', haskell);
  hljs.registerLanguage('lua', lua);
  hljs.registerLanguage('julia', julia);
  hljs.registerLanguage('dart', dart);
  hljs.registerLanguage('groovy', groovy);
  hljs.registerLanguage('powershell', powershell);
  hljs.registerLanguage('x86asm', x86asm);
  hljs.registerLanguage('fortran', fortran);
  hljs.registerLanguage('lisp', lisp);
  hljs.registerLanguage('prolog', prolog);
  hljs.registerLanguage('erlang', erlang);
  hljs.registerLanguage('ocaml', ocaml);
  hljs.registerLanguage('fsharp', fsharp);
  hljs.registerLanguage('clojure', clojure);
  hljs.registerLanguage('elixir', elixir);
  hljs.registerLanguage('pascal', pascal);
  hljs.registerLanguage('vhdl', vhdl);
  hljs.registerLanguage('tcl', tcl);
  hljs.registerLanguage('nim', nim);
  hljs.registerLanguage('commonlisp', commonlisp);
  hljs.registerLanguage('coffeescript', coffeescript);
  hljs.registerLanguage('objectivec', objectivec);
  hljs.registerLanguage('vbnet', vbnet);
}